### ISSUE TITLE
2 finger horizontal swipe to switch browser tabs?

### ISSUE THREAD

**Issue by jamespo** [harshadgavali/gnome-gesture-improvements#1]
ie - the equivalent of ctrl-tab / ctrl-shift-tab

Is this possible as an option (ie - override horizontal scroll)? Would be very useful for me as horizontal scroll is rarely used.

**Comment by harshadgavali** [comment]
Sorry, that might be possible only on X11, on Wayland extension doesn't know when horizontal scroll is done on application, so it's not possible.

Btw horizontal scroll is used by some applications.
E.g.,
Browser uses it when webpage doesn't fit width. 
Chromium based browser changes tabs, on horizontal/vertical scroll on titlebar/tabbar.
GNOME web/epiphany used it to navigate history (Alt+Arrow Keys behaviour).
Chromium based browser has flag to navigate history (chrome://flags/#overscroll-history-navigation, needs to launch browser with `--enable-features=TouchpadOverscrollHistoryNavigation` argument)

**Comment by jamespo** [comment]
Ah, thank you.

**Comment by harshadgavali** [comment]
Closing this.
Tracking this in general issue for [`gesture for keyboard shortcuts` #3](https://github.com/harshadgavali/gnome-gesture-improvements/issues/3).

**Comment by 311298** [comment]
I found one way by accident, put your cursor on any chrome tab or beside "+"(new tab option) empty space. And do 2 find swipe slow up/down to change to different tabs.
PS: I am fedora 36 wayland
