### ISSUE TITLE
Improvements in detection on moving windows to side panel

### ISSUE THREAD

**Issue by jacksongoode** [harshadgavali/gnome-gesture-improvements#10]
As of now, there is a little bit of a stutter/grab when attempting to move an unmaximized window to the left/right. I understand your logic in wanting to have a user hold the gesture before allowing left/right tiling.

My suggestion as an alternative would be to detect if a user is swiping down with multiple fingers on an unmaximized window and immediately interpret this as the user wanting to tile it left or right rather than having a delay/pause. I think this would work since as of now there is no gesture associated with multi-swipes down on an unmaximized window.

**Comment by harshadgavali** [comment]
Hey @jacksongoode , I pushed new commit to main branch.
Can you confirm that's the behaviour you had in mind?

It removed delay and animation when snap left/right gesture is activated.

Reason for adding animation was to notify that it's in snap-state, (it won't go back to maximize/minimize).
But yeah it was glitchy.

**Comment by jacksongoode** [comment]
> Hey @jacksongoode , I pushed new commit to main branch.
> Can you confirm that's the behaviour you had in mind?
> 
> It removed delay and animation when snap left/right gesture is activated.
> 
> Reason for adding animation was to notify that it's in snap-state, (it won't go back to maximize/minimize).
> But yeah it was glitchy.

Really nice and fluid, exactly how I imagined it! I tested it across a number of cases and it looks good.

**Comment by harshadgavali** [comment]
Thanks for confirmation.
Closing this now.
