### ISSUE TITLE
[Feature Request] Toggle for the App Grid gesture

### ISSUE THREAD

**Issue by ActuallyNotGelb** [harshadgavali/gnome-gesture-improvements#102]
I find this extension very intriguing but, in my case, I only use the extension for changing the swipe speed (I think the pinch gestures aren't really working on my old laptop, oops). That said, I can certainly see the potential of it, and will look into it more, once I get a laptop with a better touchpad.

However, I believe there should be an option to enable/disable the downward (or upward, if you toggle "revert direction") gesture to open the app grid.  Don't see why it wouldn't be included.

Nonetheless, thank you!

**Comment by harshadgavali** [comment]
Hi @ActuallyNotGelb , option(see in Misc Tab) to change cyclic gesture is added in version 23.
https://github.com/harshadgavali/gnome-gesture-improvements/issues/90

**Comment by ActuallyNotGelb** [comment]
Seems like I hadn't gotten the update until this morning, I'm sorry. This is a huge improvement, tysm!!
