### ISSUE TITLE
[Feature] Triple touch title bars to drag windows

### ISSUE THREAD

**Issue by jacksongoode** [harshadgavali/gnome-gesture-improvements#11]
This might be out of the scope of this extension but I had always imagined it would be cool to incorporate a three-finger touch to drag windows when the cursor is hovered over the windows title bar. 

This [project](https://github.com/do-sch/gnome-shell-touchpad-window-move) might have some insights?

**Comment by harshadgavali** [comment]
This wouldn't be very useful feature though (if only multi-touch on title-bar is supposed to move window).
We can already drag window by grabbing title-bar (granted grab area is small for some windows).

But still multi-finger tap gestures aren't reported by libinput for touchpad(it reports only on touchscreen) and mutter only reports taps on top-panel(might have changed).
So this is not possible.

Holding fingers anywhere on window for few seconds on touchpad and then swiping to move window might be useful, but it can't be implemented at the moment.

**Comment by jacksongoode** [comment]
Hmm, I see your points. I think it would be better to hold off on this idea then.
