### ISSUE TITLE
Does not support GNOME 43

### ISSUE THREAD

**Issue by rajudev** [harshadgavali/gnome-gesture-improvements#123]
I had to disable this extension on after an upgrade to GNOME 43. 
Hoping that a new release will happen with GNOME 43 support

**Comment by michalmielczynski** [comment]
me too. This worked great under 42 giving global back/forth shortcut which I really miss now.

**Comment by harshadgavali** [comment]
Hey I don’t have access to GNOME 43 right now. 
So I can’t test #120 yet. Can you test the changes just by modifying metadata.json if possible?(And comment on PR whether you have any issues)

**Comment by evgen-p-at-gorgany** [comment]
> Can you test the changes just by modifying metadata.json if possible?

For those who unfamiliar with extensions here's location of this file:
`$HOME/.local/share/gnome-shell/extensions/gestureImprovements@gestures/metadata.json`

**Comment by michalmielczynski** [comment]
oh, wow. Simply changing the metadata.json
`"shell-version": [
    "43"
  ],`

does the trick!

**Comment by rajudev** [comment]
I installed it manually by after editing `metadata.json`. 
It installed fine, but the gestures are not working for me. 
For some reason, none of the gestures are working.

**Comment by tswaehn** [comment]
for me the trick from @michalmielczynski worked fine.

**Comment by xevilstar** [comment]
please release a patched official version

**Comment by ChrisErnovsky** [comment]
> oh, wow. Simply changing the metadata.json `"shell-version": [ "43" ],`
> 
> does the trick!

**[Changing the number of version](https://github.com/harshadgavali/gnome-gesture-improvements/pull/120/files)** (before manual installation) is also necessary to avoid conflicts with extensions manager (Fedora 37 beta). After that - everything works like a charm. Great job!

**Comment by OperationNorthwoods** [comment]
On the GNOME extensions website it allows me to disable version checking and force-enable this extension. Works like a charm for me, as a temporary solution tell the an update is released.

**Comment by 0versun** [comment]
After changing metadata its work as expected on manjaro gnome 43, but it will be better to fix this in repo. Thanks

**Comment by xevilstar** [comment]
> After changing metadata its work as expected on manjaro gnome 43, but it will be better to fix this in repo. Thanks

**Comment by harshadgavali** [comment]
Thank you everyone for patience . 
Supported version was published to extensions website a month ago.

Closed by #120
