### ISSUE TITLE
Tiling gestures do not work

### ISSUE THREAD

**Issue by Samuel789** [harshadgavali/gnome-gesture-improvements#130]
Gnome 42.4 - Wayland - Pop OS 22.04 LTS

Tiling gestures do not seem to work properly. The gesture seems to be recognized with the window outline boxes moving to the left/right, but the gesture does not apply when my fingers come off the touchpad (see video). As far as I can tell, all other gestures are working properly. Moving windows to the left or right manually with the mouse does correctly trigger tiling as per default Gnome behaviour.

[Screencast from 12-10-22 11:23:18.webm](https://user-images.githubusercontent.com/1827888/195318997-00192774-5f86-4508-8d1c-79c48d01e852.webm)

**Comment by harshadgavali** [comment]
Hi,
Sorry but this extension only supports GNOME shell, heavily modified shells are not supported.

**Comment by Samuel789** [comment]
@harshadgavali Thanks for responding, this bug occurs with all extensions disabled as well (see dconf extension setting):
[Screencast from 12-10-22 12:22:07.webm](https://user-images.githubusercontent.com/1827888/195331563-b1cbf330-9aef-480e-9e50-3aa1200d6cd8.webm)

**Comment by harshadgavali** [comment]
Hey @Samuel789 
Issue probably isn’t with conflict with extensions. 
It might be related to different keybindings for tiling. See #25 

Otherwise issue is most likely with how PopOs used to ship heavily patched gnome-shell (don’t know if it’s changed), for which I can’t help sorry.

**Comment by Samuel789** [comment]
@harshadgavali This was exactly the problem, thanks!
The default value of these in PopOs is:
`['<Primary><Super>Left', '<Primary><Super>KP_Left', '<Primary><Super>h']`
and
`['<Primary><Super>Right', '<Primary><Super>KP_Right', '<Primary><Super>l']`

Changing to:
`['<Super>Left', '<Super>KP_Left', '<Primary><Super>h']`
and
`['<Super>Right', '<Super>KP_Right', '<Primary><Super>l']`
fixed the problem.
