### ISSUE TITLE
Three-finger swipe with Advanced Alt-Tab Window Switcher extension

### ISSUE THREAD

**Issue by Shoggomo** [harshadgavali/gnome-gesture-improvements#134]
The [Advanced Alt-Tab Window Switcher](https://github.com/G-dH/advanced-alttab-window-switcher) extension allows to customize the alt tab window switcher. The customizations are not visible, when using the three-finger swipe gesture, though.
It seems, as if AATWS changes the global `WindowSwitcherPopup` class (as seen [here](https://github.com/G-dH/advanced-alttab-window-switcher/blob/main/extension.js#L57)). 
So could this be integrated in this extension?

**Comment by harshadgavali** [comment]
Tracking this in #9
