### ISSUE TITLE
Extra three finger swipe options

### ISSUE THREAD

**Issue by ChristiaanWewer** [harshadgavali/gnome-gesture-improvements#135]
Hi, it would be nice if a three finger swipe could be added, such as to tile the window on the right and left side of the display. That is an option i really miss.
Thanks for the great work,

**Comment by harshadgavali** [comment]
Hi @ChristiaanWewer,
This feature(tile window) is already available in form of 'inverted T' gesture.

To tile a window first swipe down a little and then swipe left/right (without lifting fingers up) to tile a window.
But only non-maximised window can be tiled using this feature.

So if window is maximised, we need to do full swipe down to un-maximise it first, then tile gesture can be used.
