### ISSUE TITLE
Three and four finger tap gesture

### ISSUE THREAD

**Issue by sidevesh** [harshadgavali/gnome-gesture-improvements#143]
Would it be possible allow setting actions for 3 or 4 finger tap,
this would allow for things like showing the notification panel on 3 finger tap and settings menu on 4 finger tap,
which is something Windows does and is really helpful.

**Comment by harshadgavali** [comment]
Hey @sidevesh,
I had tried to see if something like this can be implemented, but unfortunately it's not possible on Wayland.
On Wayland extension don't get notified when tap action is performed.
