### ISSUE TITLE
Impossible to have window switch and app gesture at the same time

### ISSUE THREAD

**Issue by Yasso9** [harshadgavali/gnome-gesture-improvements#158]
Is it possible to replace the 4 gestures workspace switching by the app gesture ?

Currentltly here is what I have : 
- 3 fingers gesture swipe up/down goes in overview/app grid
- 3 fingers gesture swipe left/right switch window.
- 4 fingers gesture swipe up/down minimize/maximize window.
- 4 fingers gesture swipe left/right switch workspace

I ddo not need to move workspace with gestures, but I need to use app gestures instead.
I can have app gesture in 3 finger swipe if I disable window switching but I want to keep this latter.
If I disable "4 finger gestures for workspace switching" I have the workspace switching in 3 finger swipe but still no app gestures swipe.

Here are my current settings  :

![Screenshot from 2023-01-31 22-20-06](https://user-images.githubusercontent.com/63962731/215885899-c2c91296-1039-4242-a6bb-760ca08cc585.png)
![Screenshot from 2023-01-31 22-31-09](https://user-images.githubusercontent.com/63962731/215887855-6270bde9-fb3b-497b-bb2f-1148abaf1ba4.png)
![Screenshot from 2023-01-31 22-31-13](https://user-images.githubusercontent.com/63962731/215887867-13965280-3641-4121-a9bb-f29377f15108.png)

I'm on gnome 43.2 with Manjaro 22.0.1 and Gnome Gesture Improvements version 34

Thanks !

**Comment by harshadgavali** [comment]
Hi sorry for late reply.
App gestures are implemented using "hold-then-swipe" gesture. Basically hold 3/4 fingers on touchpad for few moments and then swipe left-right. (in your case since you have switch window with 3 fingers, app gesture will be triggerd using 3 fingers as well).

**Comment by Yasso9** [comment]
Ooh thanks my bad for not knowing that I need to hold for app gestures. Thanks a lot !!! I will close the issue as this is good for me.
