### ISSUE TITLE
[Feature Request] Ability to use both window switching and going backward

### ISSUE THREAD

**Issue by HubKing** [harshadgavali/gnome-gesture-improvements#164]
It is very helpful to be able to use three-finger horizontal swipe to go back/forward on FireFox and file manager, etc. (FireFox's in-built to-finger go back/forward can be very easily erroneously triggered, and I have disabled it.) But I do wish I could use some sort of gesture to switch to previous/next app.

There could be many ways, but one way I thought about is defining some sort of special area on the trackpad where the three-finger horizontal swipe is considered window switching, not going back/forward. For example, how about the bottom area of the trackpad? I don't usually perform the gesture at the bottom area to go back/forward. Also that is somewhat similar to Android/iPad's gesture. You see, on both Android/iPad, if you horizontally swipe near the bottom of the screen, it switches the app, so this logic would not feel too weird to a lot of users, I hope.

**Comment by harshadgavali** [comment]
Hi, sorry for late reply.
As of now we can use both switch apps and go back-forward in app gesture.
* To switch app default is 3 finger left-right swipe
* To go back-forward enable app-gestures, and customise the app for which you want to add gesture.
  * To trigger this gesture, do the "hold-then-swipe" gesture. Basically hold 3 fingers on touchpad for few moments and then swipe left-right. 

> I thought about is defining some sort of special area on the trackpad where the three-finger horizontal swipe   

When I decided to add app gestures, libinput or mutter (they are providing information when swipe happens) didn't have capabilities to provides coordinates of swipe, so it wasn't possible.
Hence the use of "hold-then-swipe" gesture.
