### ISSUE TITLE
[REQUEST/QUESTION] Copy same gesture behavior on touchpad -> touchscreen?

### ISSUE THREAD

**Issue by wittware** [harshadgavali/gnome-gesture-improvements#172]
I use a 2-in-1 laptop/tablet, and having a touchscreen-gesture-based alt+tab feature exactly like the window switcher feature in this extension would be a life saver. Is it possible to do this with this extension?

**Comment by wittware** [comment]
I know this is possible using touchegg and Touche to configure it, so I doubt it'd be impossible to just add a setting to apply the same touchpad config to touchscreen, but I don't know how big of a project that might be.

**Comment by harshadgavali** [comment]
Unfortunately I can't add features related to touchscreen because I don't have device to test them.

[GNOME](https://help.gnome.org/users/gnome-help/stable/touchscreen-gestures.html.en) does have in built feature to switch application: 
> Hold three fingers on the surface while tapping with the fourth.
