### ISSUE TITLE
App switching should consider user preference for multitasking across workspaces

### ISSUE THREAD

**Issue by wroyca** [harshadgavali/gnome-gesture-improvements#177]
App switching ought to align with the user's preferences for multitasking. At present, only the apps from the present workspace are displayed, neglecting the user's app switching preference to encompass apps from all workspaces:

![image](https://user-images.githubusercontent.com/91024200/233463186-f70f4f42-a8a5-45f0-a4f4-fa715a6a4dcb.png)

**Comment by harshadgavali** [comment]
Hi @wroyca,
Although extension calls it app-switching, it's actually window-switching.
GNOME has two different settings for both, but setting for window-switching isn't exposed through GUI.

Using following command you can enable hidden setting to include all _windows_ in window-switcher.
```
gsettings set org.gnome.shell.window-switcher current-workspace-only false
```
This is currently documented in README of this repository, but I decided to follow GNOME and not expose this in extension's settings.

**Comment by wroyca** [comment]
> Hi @wroyca, Although extension calls it app-switching, it's actually window-switching. GNOME has two different settings for both, but setting for window-switching isn't exposed through GUI.
> 
> Using following command you can enable hidden setting to include all _windows_ in window-switcher.
> 
> ```
> gsettings set org.gnome.shell.window-switcher current-workspace-only false
> ```
> 
> This is currently documented in README of this repository, but I decided to follow GNOME and not expose this in extension's settings.

Whoops, I totally missed that - thank!
