### ISSUE TITLE
Gnome 46 update?

### ISSUE THREAD

**Issue by Neo-29** [harshadgavali/gnome-gesture-improvements#211]
I kmow there'sa zip file for 45

Unfortunately it doesn't work anymore

Can someone provide a workaround?

**Comment by icepie** [comment]
same issue

**Comment by jamespo** [comment]
You can try this at your own risk, no support given:

https://github.com/jamespo/gnome-gesture-improvements/releases/tag/gnome46

**Comment by Neo-29** [comment]
> You can try this at your own risk, no support given:
> 
> https://github.com/jamespo/gnome-gesture-improvements/releases/tag/gnome46

Perfectly working here.Tks a lot
