### ISSUE TITLE
Consider a release in the AUR repository

### ISSUE THREAD

**Issue by zilexa** [harshadgavali/gnome-gesture-improvements#24]
Many Gnome extensions are also available in the Arch User Repository (not a distribution repository). 
The benefit for users of Arch based distributions such as Manjaro: you can easily find and install your extension in 1 single location: the 'app store', for example on Manjaro the "Add/Remove programs" or Pamac tool, which allows you to discover, install and update system packages, apps in the official repository and AUR packages (even Flatpak can be enabled). 

Another major benefit is that the extension will be updated by the system together with system and other app updates. 

Currently, there are a few other old and outdated gesture extensions available when a user searches for it, as AUR. It would be a lot easier to discover your extension + keep it updated if it was available as AUR.

**Comment by yochananmarqos** [comment]
[Done](https://aur.archlinux.org/packages/gnome-gesture-improvements/).

**Comment by harshadgavali** [comment]
@yochananmarqos 
Thank you so much for these!! I haven't tested them aur packages yet.
But for https://aur.archlinux.org/packages/gnome-x11-gesture-daemon/
On line 40
```code
install -Dm644 "$_name.service" -t "$pkgdir/usr/lib/systemd/system"
```

I think it should be
```code
install -Dm644 "$_name.service" -t "$pkgdir/usr/lib/systemd/user"
```

I'll test them.
Btw were are these files hosted (To create pull request), (Can you share tutorial/guide for this, please? I'm not familar with AUR structure).

**Comment by yochananmarqos** [comment]
You're right it should be a user service, just fixed it.

Aurweb doesn't support PR's, unfortunately. It can be set as a remote, but I never set it up that way.

I can add you as a Co-Maintainer if you have an account. 

See [here](https://wiki.archlinux.org/title/AUR_submission_guidelines#Authentication) for more info.

**Comment by zilexa** [comment]
@harshadgavali is linking to a different package (the old X11 gestures).

But thanks for creating this new package as AUR!

**Comment by harshadgavali** [comment]
@yochananmarqos 
Thank you so much again!!
Can you add me Co-Maintainer for both packages? my account [harshadgavali](https://aur.archlinux.org/account/harshadgavali) ?

@zilexa I was linking optional dependency package, extension depends on it for running on X11.

**Comment by yochananmarqos** [comment]
@harshadgavali Done.

**Comment by yochananmarqos** [comment]
@harshadgavali Please revert this [commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-gesture-improvements&id=f3acdb640e74f2014251f79a91c993765069b4de), the schema file does indeed need to be installed there when an extension is installed to the system.

Why did you remove the message about enabling the service?

**Comment by harshadgavali** [comment]
@yochananmarqos I tested on ManjaroVM schema file was not necessary I think(it was also giving warning so I removed it),
compiled schema is present in zip anyway.   
[arc-menu-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gnome-shell-extension-arc-menu-git) also doesn't need it I think.
If you're facing issue with it, please revert the change.

Enabling service is not necessary, as service will be automatically started by extension on X11 session(this way, on wayland it won't be running.)

**Comment by yochananmarqos** [comment]
@harshadgavali Ah, I see. Some extensions won't work properly unless the gschema file is installed in the glib folder. I guess it must depend on the extension. I normally symlink it for every extension I package just to make sure.

I see now your README states the service will be automatically enabled. I'm just so used to having to enable services manually. How does the extension do it?

**Comment by harshadgavali** [comment]
@yochananmarqos 
Oh thanks for mentioning pkgrel .

Since service in installed in `user` folder instead of `system`, it can be started/stopped without password
https://github.com/harshadgavali/gnome-gesture-improvements/blob/c2191992fdc62949fab438f6c910004baed4fe9c/extension/src/utils/dbus.ts#L72

Another way would be to make service dbus-activatable (if service must be installed in `system` folder)
https://docs.fedoraproject.org/en-US/packaging-guidelines/Systemd/#activation_dbus

**Comment by yochananmarqos** [comment]
@harshadgavali Oh neat. I'll have to look closer tomorrow. I wanted to figure out how to do the same with `gnome-shell-extension-x11gestures`. I'll have to poke @JoseExposito about it.

**Comment by JoseExposito** [comment]
I'd need to add D-Bus activation upstream:
https://github.com/JoseExposito/touchegg/issues/456

The Fedora guys already requested it, but I have not found the time to implement it...
