### ISSUE TITLE
Snap/half-tile a window issue

### ISSUE THREAD

**Issue by Saldios** [harshadgavali/gnome-gesture-improvements#25]
I cant use de half-tile gesture, when a used make the animation but dont set the wndows in tile, just change the workspace, if i tile to the left, change to the left workspace, if i do it to the right, same, just change workspace to the right.

**Comment by harshadgavali** [comment]
Hi, tile gesture relies on keyboard shortcuts(Super+Left and Super+Right) due to lack of api from mutter.

Can you give me output of following command (to know what are keyboard shortcuts for tiling)
1. ```gsettings list-recursively | grep -i toggle-tile```
2. ```gsettings list-recursively | grep -i --fixed-strings "<Super>Right"```

**Comment by Saldios** [comment]
I change the shortcuts tu Alt+Left and Alt+Right, and use the Super+Left and Super+Right to change workspace, I change it back and work just fine, thanks!

**Comment by thyttan** [comment]
I just recently had this problem as well. I didn't really connect it to having changed keybindings but going into keybindings and resetting as suggested worked for me also. Thanks!

**Comment by Hedronmx** [comment]
Could it be possible to change the keyboard shortcut the gesture uses? I use window left or right to change workspaces
