### ISSUE TITLE
Gesture Switch

### ISSUE THREAD

**Issue by LexxFade** [harshadgavali/gnome-gesture-improvements#26]
Would be a nice option to switch 3-fingers to control workspace and 4-fingers to control window manipulation.

**Comment by harshadgavali** [comment]
Option is there in preferences.
Can you toggle both option starting with `4-finger gesture for...`?
First and Third option in following screenshot (might be different order for you)
![image](https://user-images.githubusercontent.com/30668911/141836117-ff8bdf50-6ae9-4064-95db-55865d685f89.png)
