### ISSUE TITLE
[Feature request] Use both 3- and 4-fingers gestures for the same action

### ISSUE THREAD

**Issue by carallo** [harshadgavali/gnome-gesture-improvements#31]
Hi @harshadgavali!

First of all thank you for this great extension.

I wanted to know if it would be possible to add the option of enabling 4-fingers gestures without overriding 3-finger ones.
What I mean is that, when enabling 4-finger gestures for overview navigation and workspace switching, they do not disable 3-finger gestures for the same actions, but instead work parallely to those.

I have some reasons for this. First of all my laptop doesn't probably have such a sensitive touchpad. This means that doing 3 and 4 fingers gestures sometimes gets confused by the computer, so for example, instead of going into overview I get maximising gesture. If I disable 3-fingers gestures completely sometimes the 4-finger ones simply don't get recognised, it is not so immediate.
Secondly, I find that 3 or 4 finger gestures much depend on the position of my hand and size of the touchpad, so sometimes I find it more confortable to do a 3-fingers one, and other times a 4-finger one.
Thirdly, having gestures for maximising windows is surely convenient, but to me it's more important to have a very good working gesture for overview and workspace switching. And this option might be useful for people like me who doesn't have a super-sensitive or new generation touchpad.

I hope it is possible and not complicated to implement.

Anyway, thank you so much again!

**Comment by harshadgavali** [comment]
Hi @carallo 
Just to be sure you want
* only two swipe gestures (workspace and overview related)
* and both these gestures to be available with 3 and 4 as well fingers.

Is that correct?

Yes it's possible to add them, Behaviour for older version(when `Window manipulation` gesture wasn't available) was that both 3 and 4 finger vertical gestures are used for overview navigation.

But I need to spend little time to decide how to do that without breaking existing configurations.

In meanwhile, You can disable `Window manipulation` gesture and also disable 4 finger gesture for overview navigation, to get have 3 finger gesture for overview navigation and disable maximize gesture.

**Comment by kyteinsky** [comment]
Something like this may be easy for everyone to understand and control. This can also solve this issue, but would require a whole lot of code rewrite and restructuring. Your call.

![touche_ss](https://user-images.githubusercontent.com/20724224/143495804-f8677102-49c4-425e-b8d5-a515d4d5f3d7.png)
Source: [link](https://github.com/JoseExposito/touchegg)

**Comment by carallo** [comment]
Hi @harshadgavali,

> Hi @carallo Just to be sure you want
> 
>     * only two swipe gestures (workspace and overview related)
> 
>     * and both these gestures to be available with 3 and 4 as well fingers.
> 
> 
> Is that correct?

Exactly this!
Thanks for your fast reply. I'm trying the configurations you told me to find the right configuration but yes, for my use-case if you could add that option it would be amazing. I hope it's not too complicated.
@kyteinsky I have used touchegg on my brother's laptop and is very convenient to configure gestures. Unfortunately I'm not a programmer and cannot help, so I won't be asking for anything else :) But if you need me for some testing I can do that.

Thank you so much for taking this into consideration!

**Comment by harshadgavali** [comment]
Tracking in more general issue #43
