### ISSUE TITLE
[Feature Request]  gesture for overview navigation - follow Android & iOS gesture

### ISSUE THREAD

**Issue by zilexa** [harshadgavali/gnome-gesture-improvements#32]
On Android and iOS, swiping up shows the App Drawer (Android)/Homescreen-with-all-apps (iOS). 
With Gnome Gesture Improvements, swiping down shows App Grid, which for most people can be recognised as the App Drawer/homescreen-with-all-apps of their phone and tablet.

Would it be possible to change (or allow us to change) the order of the gesture?

Currently: 
Swipe up once: Overview
Swipe up twice: Appgrid
**Swipe down: immediately Appgrid (skipping Overview)** 

Request: 
**Swipe up: immediately Appgrid (skipping Overview)**
Swipe down once: Overview 
Swipe down twice: Appgrid 

It has been a while since I used a Macbook (2019) but I believe swiping down once = Overview as well. 

Just to prevent users from having to adapt their behavior and have similar/common gestures across platforms.

**Comment by harshadgavali** [comment]
Thanks @zilexa ,
I'll add this in next version.

**Comment by harshadgavali** [comment]
This is available in version 20 for gnome 42+ .
