### ISSUE TITLE
How to keep the extension up to date automatically?

### ISSUE THREAD

**Issue by zilexa** [harshadgavali/gnome-gesture-improvements#33]
On Manjaro, I discovered I can install this extension through AUR (Arch User Repository), either via "Install/Remove Programs", which is Pamac, or via bash: `sudo pamac install --no-confirm gnome-gesture-improvements`.
AUR stuff is auto updated by Pamac. 

I am just wondering what the best way is to install this extension in such a way, it will be automatically updated? 

I am not sure how the AUR version of this extension is updated, if it is linked to your repository (but you have no /releases) or if someone takes care of this manually, in which case I am dependent on that person to update the AUR version whenever you release a new version.

**Comment by harshadgavali** [comment]
I’ve updated last version in aur, by creating package from commit which was uploaded to extension website(EGO).
But I’m not sure how to handle dependency when Arch and Manjaro has different versions of gnome.
So I’d recommend to install from extension website(which handles dependency automatically).
 
Aur package was discussed here https://github.com/harshadgavali/gnome-gesture-improvements/issues/24#issuecomment-964512641 .
