### ISSUE TITLE
Switch between windows only switches between last 2 activated windows

### ISSUE THREAD

**Issue by jaygambrel** [harshadgavali/gnome-gesture-improvements#35]
Affected OS: Manjaro - Gnome
Gnome Version: 41.1
Session Type: Wayland

Enabled/Disabled Settings

Window switching: enabled
4-finger gestures for workspace switching: enabled or disabled does not affect bug behaviour
4-finger gestures for overview navigation: enabled or disabled does not affect bug behaviour

Observed Behaviour

When gesturing horizontally to switch between windows, it only switches between the last 2 windows that have been active instead of all open windows.  It doesn't seem to matter whether 4-finger gestures for workspace switching is enabled or not.  If it is, then a 3 finger horizontal swipe switches between the last 2 active windows.  If it is not enabled then a 4 finger horizontal swipe switches between the last 2 active windows.

Activating different windows using the touchpad/mouse by clicking on them then seems to reset which were the last 2 activated windows and using the horizontal swipe to switch between windows will again only switch between the last 2 activated windows.

Thank you very much for this very helpful extension!

**Comment by harshadgavali** [comment]
Hello,
You have to wait (don’t end swipe up) for switcher to show when doing gesture (150 milliseconds, configurable in preference).
Then you can switch to any window.
Similar to Alt+Tab behavior with keyboard shortcuts.

Or did I misunderstood something?

**Comment by jaygambrel** [comment]
Oops. I should have read the instructions more closely. Thank you for
clarifying and for making such a useful extension.
