### ISSUE TITLE
Doesn't work on Fedora 35 Gnome 41.1 + X11

### ISSUE THREAD

**Issue by eypsume** [harshadgavali/gnome-gesture-improvements#36]
the  gesture_improvements_gesture_daemon.service  daemon works fine on starting by user.
now this gnome extension get failed. 
I enabled it as using gnome-extensions enable gestureImprovements@gestures
But  there was going to be disabled always.
I run Gnome 41.1 on X11 on Fedora 35 latest updated.

**Comment by harshadgavali** [comment]
Can you share output of following steps?
1. Disable extension
1. Open two terminals and run following commands
    1. `journalctl -f -o cat /usr/bin/gnome-shell`
    1. `journalctl --user -f -o cat -u gesture_improvements_gesture_daemon.service` 
1. Enable extension
2. Perform any gesture
3. Stop commands, and share output

**Comment by eypsume** [comment]
Well, here are that logs:
**i. $ journalctl -f -o cat /usr/bin/gnome-shell**
GNOME Shell started at Sun Dec 05 2021 12:50:15 GMT+0900 (대한민국 표준시)
Registering session with GDM
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Timelines with detached actors are not supported
^C


**ii.$ journalctl --user -f -o cat -u gesture_improvements_gesture_daemon.service**
Started gesture improvements Gesture Daemon.
Stopping gesture improvements Gesture Daemon...
Stopped gesture improvements Gesture Daemon.
Started gesture improvements Gesture Daemon.
libinput error: event9  - PNP0C50:00 04F3:30AA Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
Stopping gesture improvements Gesture Daemon...
Stopped gesture improvements Gesture Daemon.
gesture_improvements_gesture_daemon.service: Consumed 1.743s CPU time.
Started gesture improvements Gesture Daemon.










libinput error: event18 - PNP0C50:00 04F3:30AA Touchpad: client bug: event processing lagging behind by 34ms, your system is too slow
^C



I get any gestures such as three finger swipe .. at that above empty lines

**Comment by eypsume** [comment]
Also, detail material here:
$ echo $XDG_SESSION_TYPE
x11

$ uname -ai
Linux fedora  5.15.5-200.fc35.x86_64 #1 SMP Fri Nov 26 00:46:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ dmesg -x | egrep "touch"
kern  :info  : [    2.007851] hid-multitouch 0018:04F3:30AA.0006: input,hidraw7: I2C HID v1.00 Mouse [PNP0C50:00 04F3:30AA] on i2c-PNP0C50:00z

$ dnf list installed libinput
libinput.x86_64                                  1.19.2-1.fc35                                   @updates

**Comment by harshadgavali** [comment]
@eypsume
In latest version of extension, output of gnome-shell should contain debug statement like
```
>  journalctl -f -o cat /usr/bin/gnome-shell
[DEBUG]:: in function subscribe at gestures/src/utils/dbus.js:105:13
	"starting dbus service 'gesture_improvements_gesture_daemon.service' via spawn"
```
Are you sure you have installed latest version from extensions website?
Also output of both commands doesn't say any failures, how did you know about extension failure?
Do you mean there's no failures, but gestures don't work?

What's output of `libinput debug-events` when performing swipe gesture ?
It should be like this when doing 3 finger swipe gesture.
```
> libinput debug-events
-event5   GESTURE_SWIPE_BEGIN     +5.422s	3
 event5   GESTURE_SWIPE_UPDATE    +5.422s	3  9.17/-3.29 ( 9.16/-3.29 unaccelerated)
 event5   GESTURE_SWIPE_UPDATE    +5.429s	3  5.21/-1.76 ( 5.20/-1.75 unaccelerated)
 event5   GESTURE_SWIPE_UPDATE    +5.436s	3 20.44/-6.25 (17.20/-5.26 unaccelerated)
 event5   GESTURE_SWIPE_UPDATE    +5.443s	3 16.01/-4.73 (11.88/-3.51 unaccelerated)
 event5   GESTURE_SWIPE_UPDATE    +5.450s	3 13.18/-3.97 (11.65/-3.51 unaccelerated)
 event5   GESTURE_SWIPE_UPDATE    +5.457s	3 18.09/-6.07 (14.37/-4.82 unaccelerated)
 event5   GESTURE_SWIPE_UPDATE    +5.464s	3  6.07/-2.04 ( 5.54/-1.86 unaccelerated)
 event5   GESTURE_SWIPE_END       +5.471s	3
```

**Comment by eypsume** [comment]
There is nothing from 'journalctl -f -o cat /usr/bin/gnome-shell' after get started.
First I run the command and then I do the second  journalctl --user -f -o cat -u gesture_improvements_gesture_daemon.service.
And then, I run the daemon service by systemctl --user start gesture_improvements_gesture_daemon.service.
At this time, the second command output 'Started gesture improvements Gesture Daemon.'
And I enable the extension by gnome-extensions enable gestureImprovements@gestures.
Now I try any touch gestures and then the second command output :
,,
libinput error: event18 - PNP0C50:00 04F3:30AA Touchpad: client bug: event processing lagging behind by 34ms, your system is too slow
Stopping gesture improvements Gesture Daemon...
Stopped gesture improvements Gesture Daemon.
gesture_improvements_gesture_daemon.service: Consumed 1.793s CPU time.
Started gesture improvements Gesture Daemon.
libinput error: event5  - CATEX TECH. 87EC-XRGB: client bug: event processing lagging behind by 24ms, your system is too slow.
,,
Above log, the daemon service seems to be started double times.
Anyway, until now, the first command side doesen't output anything  and never continuously.

>>Are you sure you have installed latest version from extensions website?
I installed version 19 with Gnome41 from the Firefox gnome extension plugin. download latest Gnome41 with 19.  Once done, I try disable or enable through command such as above present.

>>Also output of both commands doesn't say any failures, how did you know about extension failure?
Do you mean there's no failures, but gestures don't work?
Yes, and I think there is meaningful with above libinput error includes daemon restarting.

>> What's output of libinput debug-events when performing swipe ?
Yes, when I try three fingers swipe vertically and horizontally.
It might be event 5 for vertically and event 17 for horizontally.
and the libinput get slow in doing for each action, due to cause late response.

Here is second time log from journalctl --user -f -o cat -u gesture_improvements_gesture_daemon.service
,,
$ journalctl --user -f -o cat -u gesture_improvements_gesture_daemon.service
libinput error: event9  - PNP0C50:00 04F3:30AA Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
Stopping gesture improvements Gesture Daemon...
Stopped gesture improvements Gesture Daemon.
gesture_improvements_gesture_daemon.service: Consumed 1.743s CPU time.
Started gesture improvements Gesture Daemon.
libinput error: event18 - PNP0C50:00 04F3:30AA Touchpad: client bug: event processing lagging behind by 34ms, your system is too slow
Stopping gesture improvements Gesture Daemon...
Stopped gesture improvements Gesture Daemon.
gesture_improvements_gesture_daemon.service: Consumed 1.793s CPU time.
Started gesture improvements Gesture Daemon.
libinput error: event5  - CATEX TECH. 87EC-XRGB: client bug: event processing lagging behind by 24ms, your system is too slow
libinput error: event5  - CATEX TECH. 87EC-XRGB: client bug: event processing lagging behind by 17ms, your system is too slow
libinput error: event5  - CATEX TECH. 87EC-XRGB: client bug: event processing lagging behind by 21ms, your system is too slow
libinput error: event5  - CATEX TECH. 87EC-XRGB: client bug: event processing lagging behind by 15ms, your system is too slow
libinput error: event5  - CATEX TECH. 87EC-XRGB: client bug: event processing lagging behind by 13ms, your system is too slow
libinput error: event5  - CATEX TECH. 87EC-XRGB: WARNING: log rate limit exceeded (5 msgs per 60min). Discarding future messages.
libinput error: event17 - PNP0C50:00 04F3:30AA Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
libinput error: event17 - PNP0C50:00 04F3:30AA Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
libinput error: event17 - PNP0C50:00 04F3:30AA Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
libinput error: event17 - PNP0C50:00 04F3:30AA Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
libinput error: event17 - PNP0C50:00 04F3:30AA Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
libinput error: event17 - PNP0C50:00 04F3:30AA Touchpad: WARNING: log rate limit exceeded (5 msgs per 24h). Discarding future messages.

,,

**Comment by eypsume** [comment]
what's the failure? Gesture doesn't work , so I wrote this bug subject as 'Doesen't work .."

**Comment by harshadgavali** [comment]
Sorry I misunderstood some things.

1. If you installed extension by downloading zip file, instead of toggling button in extension website
OR you updated through extension website
**both of these actions require restart**

1. (make sure extension appears in https://flathub.org/apps/details/org.gnome.Extensions app)
(or it appears in output of `gnome-extensions list`)
I think this is main issue.

1. **Also make sure you are in `input` group**
As mentioned in REAME on https://github.com/harshadgavali/gnome-x11-gesture-daemon
```
# run command to add user to `input` group
> sudo usermod -aG input $USER
```
This also requires restart
```
~> groups # to verify which group you are in
wheel libvirt input
```
1. And you're not expected to start by service manually (extension does that) (sorry for confusion, I'll add this to README)

## output of journalctl
When extension is enabled, output of `journalctl -f -o cat /usr/bin/gnome-shell` should have debug statement on X11.
Output:
```
>  journalctl -f -o cat /usr/bin/gnome-shell
[DEBUG]:: in function subscribe at gestures/src/utils/dbus.js:105:13
	"starting dbus service 'gesture_improvements_gesture_daemon.service' via spawn"
```

Steps to get output are. 
1. Disable extension `gnome-extensions disable gestureImprovements@gestures`
1. Run command in  `journalctl -f -o cat /usr/bin/gnome-shell` in terminal
1. In different terminal enable extension `gnome-extensions enable gestureImprovements@gestures`
1. If you don't see debug output in `journalctl` command, that means extension is not enabled

**Comment by eypsume** [comment]
I think there is no problem on my installation and testing.
I definitely did it everything your guide says.

> 1. If you installed extension by downloading zip file, instead of toggling button in extension website
OR you manually updated extension through extension website
both of these actions require restart

I installed it from extension website toggling button but NOT download .zip file.
I restarted or log out/in after installation.

> 2. (make sure extension appears in https://flathub.org/apps/details/org.gnome.Extensions app)
(or it appears in output of gnome-extensions list)
I think this is main issue.

I have used 'gnome-extension list' to find the extension ID.
that showing is like below,,
```
$ gnome-extensions list
gestureImprovements@gestures
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
launch-new-instance@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
```

>3. Also make sure you are in input group
As mentioned in REAME on https://github.com/harshadgavali/gnome-x11-gesture-daemon

Sure, I done it already when I install origin first time.
look like this, (note, I replace the real  account name to eypsume  just for privacy)
```
$ groups
eypsume wheel input

```

>1.And you're not expected to start by service manually (extension does that) (sorry for confusion, I'll add this to README)

I just tried manually to start the service when I don't see that starting message at output.

> 4.If you don't see debug output in journalctl command, that means extension is not enabled

Yeah, I never see it, I think so the extension is not enabled, 
Exactly extension website toggle button get turn-off  instantly every time  I turn-on. (I refresh the extension website to check it). I don't know the command usage how to check it.

**Comment by harshadgavali** [comment]
I'm not very familiar with commands for extension, I use extension app most of the time.
But I think all extensions are disabled by default for you.
To check
```
> gsettings get org.gnome.shell disable-user-extensions # should be false
> gnome-extensions list --enabled # this will output list of enabled extension and should contain gestureImprovements@gestures
```

Can you try enabling any other extension, which provides visual change/like arcmenu or window-list?
And see if they get enabled?

**Comment by eypsume** [comment]
It might be my gnome-extension doesn't work for any extensions.
Take a look here
```
$ gsettings get org.gnome.shell disable-user-extensions
true
```
`$ gnome-extensions list --enabled`
- empty -

```
$ gnome-extensions list --disabled
gestureImprovements@gestures
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
launch-new-instance@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com

```
>Can you try enabling any other extension, which provides visual change, like arcmenu and window-list?
And see if they get enabled?

Okay, I treid, I  enable app-menu by $ gnome-extensions enable apps-menu@gnome-shell-extensions.gcampax.github.com

and then I check that state again but the app-menu was not enabled, 
`$ gnome-extensions list --enabled`
```
$ gnome-extensions list --disabled
gestureImprovements@gestures
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
launch-new-instance@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
```
I have not use any extension after install Fedora 35 and update.
First the extension I install is your gestureImprovement. 
what's problem for me?

**Comment by harshadgavali** [comment]
Ah this is gnome issue, it sometimes automatically disables all extensions, whenever there's some failure anywhere.
To enable extensions 
```
gsettings set org.gnome.shell disable-user-extensions false
```
Or enable using extensions application (GUI) 
```
# install app
sudo dnf install gnome-extensions-app
```

**Comment by eypsume** [comment]
Wow, Gesture works fine, I can get your mention as  gsettings get org.gnome.shell disable-user-extensions should be false, 
So I set false that  by gsettings set org.gnome.shell disable-user-extensions false
and then  I do  $ gnome-extensions enable gestureImprovements@gestures.
Now extension works pretty, Thanks a lot for your all.
