### ISSUE TITLE
[Feature Request]: Pinch-out (3/4 fingers) to close application

### ISSUE THREAD

**Issue by jajex1** [harshadgavali/gnome-gesture-improvements#38]
Hello!

I would like to know if it would be possible to introduce 3 or 4 fingers pinch-out gesture to quickly close the application.

Currently I'm using your extension to Tile/Maximize applications. A quick way to close an app would be perfect to completely ditch the need to move the cursor towards the close button :).

PS: Thank you for your awesome work, I really enjoy using your software :).

**Comment by harshadgavali** [comment]
Hi @jajex1 
While it’s possible to implement, I really don’t want to do that.
Why
- It’s destructive action
- It’s non reversible action (can’t bring window back using just gestures)
- Implementing this would mean, tile or minimize gesture won’t be available 

While not the exact thing, alt+tab or minimize gesture can be used for similar thing.
Sorry.
