### ISSUE TITLE
feature request: 5 finger gestures

### ISSUE THREAD

**Issue by thyttan** [harshadgavali/gnome-gesture-improvements#41]
Feature request: In the future, I think it might be useful to be able to map 5 finger gestures as well.

I read other feature requests here and specifically about swiping for going forward/backward in e.g. browsers  (#23). If that gets implemented I think maybe it would make sense to use 5 finger gestures as well.

What I have in mind right now for settings I think would work well:
2 finger gestures: handled by underlying system and not changed by gesture improvements.
3 finger swipes: actions within a window (mostly backwards a page/forwards a page in web- and file-browsers)
4 finger swipes: window movements/tiling and window switching
5 finger swipes: workspace switching and overview navigation.

Thanks for this very useful extension!

**Comment by harshadgavali** [comment]
I don't think 5 finger gesture are possible.
In `sudo libinput debug-events`
```
> sudo libinput debug-events
....
 event5   GESTURE_SWIPE_UPDATE    +2.721s	4  0.00/-0.03 ( 0.00/-0.08 unaccelerated)
....
```
When I do fiver finger gesture libinput recognises it as four finger (`4` after +2.721 means four finger).

Sorry.

**Comment by thyttan** [comment]
Thank you for researching it! :)
