### ISSUE TITLE
Check for top panel when resizing windows

### ISSUE THREAD

**Issue by jacksongoode** [harshadgavali/gnome-gesture-improvements#5]
In some cases (such as if a user is using an extension or if an app is maximized) the top panel may not be visible. This causes issues on visualizing where the window will transition to in blue.

https://user-images.githubusercontent.com/54308792/129317271-d2d4e069-afab-47a2-993a-00e44c090d8f.mp4

**Comment by harshadgavali** [comment]
This gesture is not supposed to be activated for a fullscreen-window.
And when panel is hidden on secondary monitor. This issue doesn't happen for me.

Are using extension to hide top panel, which one ?
If yes, then this maybe tricky to fix in this extension alone.
Basically can't assume panel height is zero if panel is hidden, otherwise this will cause similar issue if one window is in fullscreen-mode and focused window is not.

**Comment by jacksongoode** [comment]
> This gesture is not supposed to be activated for a fullscreen-window.
> And when panel is hidden on secondary monitor. This issue doesn't happen for me.
> 
> Are using extension to hide top panel, which one ?
> If yes, then this maybe tricky to fix in this extension alone.
> Basically can't assume panel height is zero if panel is hidden, otherwise this will cause similar issue if one window is in fullscreen-mode and focused window is not.

Yes I'm using [Hide Top Bar](https://extensions.gnome.org/extension/545/hide-top-bar/). Is there some conflict between the height of the panel and the state of a window's maximization. Are they linked?

**Comment by harshadgavali** [comment]
It autoclosed?

Anyway, recent commit fixes this when panel is hidden using `Just Perfection` extension.
issue still occurs if panel is hidden(intelihide turned off) using `Hide Top Bar` extension.

**Comment by jacksongoode** [comment]
Yes, the bug is now fixed on disable, it's still an issue for Hide Top Bar so it might be good to reopen this issue until resolved?

**Comment by harshadgavali** [comment]
Can you check with latest changes?

**Comment by jacksongoode** [comment]
> Can you check with latest changes?

You got it! I was _just_ about to make a commit with panelBox from this https://github.com/mlutfy/hidetopbar/blob/285d953c2bb0123cfddde37a877e7ae09c88fb2e/panelVisibilityManager.js#L82

**Comment by harshadgavali** [comment]
Hey pushed change to main branch as well, with minor adjustment for multi-monitor setup.
Does this resolve issue ?
