### ISSUE TITLE
[REQ] Coverflow integration

### ISSUE THREAD

**Issue by Gouster4** [harshadgavali/gnome-gesture-improvements#60]
Hello.
Can you please add optional integration to Coverflow extension?
https://extensions.gnome.org/extension/97/coverflow-alt-tab/

Thanx.

**Comment by harshadgavali** [comment]
I had issue open for this.
But I don't have enough knowledge about algorithm to convert whole extension into typescript.

Closing this in favour of https://github.com/harshadgavali/gnome-gesture-improvements/issues/9
