### ISSUE TITLE
GNOME 42 support

### ISSUE THREAD

**Issue by sh7dm** [harshadgavali/gnome-gesture-improvements#66]
Hello, could you please test this with GNOME Shell version 42 and publish the extension for it? I want to begin using testing GNOME 42, but cannot work efficiently without this extension, so I want to ensure it won't break.
Thanks for a cool extension!

**Comment by harshadgavali** [comment]
Hi can you test https://github.com/harshadgavali/gnome-gesture-improvements/tree/gnome-42 branch?
or download zip from https://github.com/harshadgavali/gnome-gesture-improvements/actions/runs/1991997858 .

you'll need gnome-42.rc not beta for this to work?

**Comment by sh7dm** [comment]
Sorry, my system is not on 42 now. Could not try in VM because my laptop has I2C touchpad, which is not easy to pass through to VM.

**Comment by sh7dm** [comment]
If that works fine for you, release it. Thank you for responding!

**Comment by harshadgavali** [comment]
> which is not easy to pass through to VM.
Yeah, so I'm waiting for beta versions of fedora and ubuntu to test on hardware.
I have tested on fedora daily builds, but not on ubuntu since it's still on 42.beta.

I'll release after I test on both betas.

**Comment by sh7dm** [comment]
Cool, thank you! Probably this should stay open even though complete and tested, because it's still unreleased.

**Comment by gimdh** [comment]
I have a small suggestion though. Quick GNOME version check on npm manual installer would be nice to have. I was able to install main branch with no warning on GNOME 42 before finding this issue. Little warning such as 'Your GNOME shell (${version}) is not officially supported. Want to continue? (y/n)' or 'Your GNOME shell is not officially supported. Please retry with --force option.' would be perfect.

I am no expert of node and npm, so I am not sure how difficult would it be though.

**Comment by jacksongoode** [comment]
I'm not sure if it is just the `set_titlebar()` that's breaking the settings but it seems to impact some functionality as well (version 19)? Looking forward to seeing this support.

**Comment by LudvigHz** [comment]
Tested on arch with `gnome-shell 1:42.0-1` (on wayland) in the arch repos. No issues here! :ok_hand:. Thanks!

**Comment by hgaiser** [comment]
Tested on Arch repos here too, works fine :)

**Comment by danielcherubini** [comment]
working on Arch with 42

**Comment by harshadgavali** [comment]
thanks all. updated version is now available on extensions website.
it won't work on gnome 42.beta, so for anyone testing on ubuntu 22.04 beta, please update your system.

**Comment by matthijskooijman** [comment]
> it won't work on gnome 42.beta, so for anyone testing on ubuntu 22.04 beta, please update your system.

I've just installed it on a week-old 22.04 install, and it works fine there (which you probably knew, but still) :-)

**Comment by harpreetstealth** [comment]
the link has expired, please help
