### ISSUE TITLE
New idea ??

### ISSUE THREAD

**Issue by GFoniX** [harshadgavali/gnome-gesture-improvements#7]
HI, I use your extension for a few days and I have some question or idea of improvement.

First when I use "Snap/half-tile a window, " it's only working on unmaximized but can you do it for maximized windows?

And can we bind shortcut or action to a gesture? If I want for example close window use shortcut "Alt+F4".

And can you add actions to lock computer with 4 or 3 fingers down? Before using this extension I have an extension who does this, but it's old now.

And you have done a nice work, continue like this I love it!!

**Comment by harshadgavali** [comment]
Hi,
Currently tracking `gestures for keyboard shortcut` here https://github.com/harshadgavali/gnome-gesture-improvements/issues/3 .

> First when I use "Snap/half-tile a window, " it's only working on unmaximized but can you do it for maximized windows?

Currently that's intention behaviour (all gestures are used, so snap/half-tile is kinda hacky).
I'll try to correct them once [mutter MR#1830](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1830) is merged in mutter.

> add actions to lock computer  

This might get added in gnome-shell [gnome-shell Issue#4441](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4441), if not will try to add them here.
