### ISSUE TITLE
Not working on Dell XPS 15 9560 and Ubuntu 22.04

### ISSUE THREAD

**Issue by Coshibu** [harshadgavali/gnome-gesture-improvements#78]
The title says it. There seems to be no effect on trackpad gestures on the Dell XPS 9560 with Ubuntu 22.04 LTS.

**Comment by Lolimpo** [comment]
Also have xps and ubuntu 22.04, may be stacktrace could help you:
```
InternalError: buffer too small

Stack trace:
  markup_escape_text@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:21:21
  _init@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:79:24
  GIE_AppGestureSettingsRow@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:73:4
  _addAppGestureRow@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:192:18
  _init/<@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:147:76
  _init@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:147:54
  GIE_AppKeybindingGesturePrefsGroup@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:121:54
  getAppKeybindingGesturePrefsPage@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/appGestures.js:288:11
  buildPrefsWidget@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/common/prefs.js:103:59
  fillPreferencesWindow@/home/lolimpo/.local/share/gnome-shell/extensions/gestureImprovements@gestures/prefs.js:13:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by harshadgavali** [comment]
> The title says it. There seems to be no effect on trackpad gestures on the Dell XPS 9560 with Ubuntu 22.04 LTS.

Hi I don't have xps and i'm unable to reproduce this issue on my laptop.
1. Are you on Wayland or X11 display server?
1. Can you tell what exactly isn't working?
    *.  Can you also add detailed steps for reproducing this issue?
    *. What's output of `journalctl -o cat -f /usr/bin/gnome-shell` when gesture doesn't work?
1. Do gestures work on wayland without this extension?

**Comment by harshadgavali** [comment]
> Also have xps and ubuntu 22.04, may be stacktrace could help you:
 Hi @Lolimpo, your issue looks like is related to extension settings rather than extension itself, right?
 
 Issue is caused by name of some application you have (name is passed to `markup_escape_text` function).
 What apps do you have installed?
 Can you share output of following command here ?
 
 ```
 gjs --command="console.log(JSON.stringify(imports.gi.Gio.app_info_get_all().map(a => [a.get_id(), a.get_display_name()]), undefined, 2))"
 ```

**Comment by Coshibu** [comment]
Ok, I didn't realize that Ubuntu 22.04 switched last minute (on release day) back to X11 instead of wayland.  So I was on x11 afterall and didn't have the [gnome-x11-gesture-daemon](https://github.com/harshadgavali/gnome-x11-gesture-daemon) installed.

**Comment by harshadgavali** [comment]
@Lolimpo If you're still facing issue, please open new one.
And try to include output and information that might help in reproducing it in new issue.

**Comment by harshadgavali** [comment]
@Lolimpo Settings window issue is fixed on main branch, it caused by different language.
It'll be available on extensions website soon.
