### ISSUE TITLE
[Feat Req] App configure 2,3, 4 fingers action like firefox 2 siwtch tabs and 3 history?

### ISSUE THREAD

**Issue by Hideman85** [harshadgavali/gnome-gesture-improvements#88]
First of all this extension is awesome and need more stars :star: 

I read on the readme the apps are configurable and also there is a mention of browser tab switching :thinking: 
I activated the option of app having customized options when holding and then witch but the only thing I'm getting is the browser history with three fingers.
I'm wondering how I can enable also tab switching on two fingers?

Thanks in advance for your help :wink:

**Comment by harshadgavali** [comment]
Thanks :)

Unfortunately we can have only one keybinding for each app (so either tab switching or history or ...).
For tab switching, in app gesture tab select 'Tab Next/Prev' keybinding for firefox app.
Does that help?

**Comment by Hideman85** [comment]
Yes sorry I tested more and I just figured out this is either one or the other.
Then it would be more a feature request to configure 2, 3, 4 fingers option for app too.
I think in terms of UX the hold is understood so we could configure all that options isnt?

**Comment by harshadgavali** [comment]
Sorry, this is out of scope.
* 2-finger: There's no 2-finger swipe , only 2-finger scroll. And reacting externally to scroll will break some applications.
* 4-finger: App gestures don't fit with workspace gesture, so this won't be added as well. And #67 is open for 4-finger hold gesture which has more _chance_ of being added.
