### ISSUE TITLE
Feature request: Option to disable swipe down → app grid gesture

### ISSUE THREAD

**Issue by sk22** [harshadgavali/gnome-gesture-improvements#90]
I would like to be able to disable the gesture that lets you access the applications grid directly by swiping down because it doesn't feel natural to me, and sometimes app windows aren't displayed in the right size during the transition.
Thanks for this amazing extension, btw!!

**Comment by harshadgavali** [comment]
Hey @sk22. I have thought about adding different options for this.
e.g., I thought about adding following options: move between cyclic, gnome-default, desktop-overview-only or desktop-appgrid-only.

But I do want to avoid providing too many options without any significant value to avoid maintenance burden.

So why do you think it's appgrid option is not natural?
Also we can just not swipe down on desktop to not trigger it, if we're trying to swipe down on desktop means we expect some gesture exists there.

**Comment by sk22** [comment]
it happens to me that i accidentally swipe down on desktop (maybe due to lag), and i'd rather see the gnome default happening (nothing) than launching the app grid. i think it feels unnatural to me because it's the opposite direction i'm swiping.
maybe the gnome default could be the default, providing the options you proposed as opt-in enhancements? i'm open to anything, really, but i'd love to see an option to disable it.
thanks for your considerations!

**Comment by harshadgavali** [comment]
Thanks for suggestion. I have added option in `overview-nav-states` branch.
I'll merge into main branch and publish to extension site in next version if I don't encounter any issues with it.

**Comment by sk22** [comment]
sounds good, thank you!
