### ISSUE TITLE
Feature request: Smoother window close animation

### ISSUE THREAD

**Issue by sk22** [harshadgavali/gnome-gesture-improvements#91]
While I am a big fan of the (Touchegg-inspired, I assume?) window close animation, I think it could look better

* having a red border appear on the edges instead of the red box, just like Touchegg does it, OR
* if the red box had a short opacity transition when appearing (so it doesn't just appear out of nowhere)
* if the red box disappeared while getting smaller: so instead of closing the window when the box has reached a size of 0, I think it would look better if the red box just got like 75% smaller, while also transitioning to 100% opacity.

**Comment by harshadgavali** [comment]
Sorry I didn't exactly get what animation you want.
I have pushed commit for animating with opacity so widget doesn't appear out of nowhere.

If you or anybody wants different animation, please make a pull request (though keep in mind it might not get merged).
For reference: Close gesture was introduces first via #42 ,
