### ISSUE TITLE
WIndow Manipulation won't work until 4-finger gesture for overview navigation is not turned on

### ISSUE THREAD

**Issue by adhadse** [harshadgavali/gnome-gesture-improvements#99]
Currently, the gesture settings app let user set Window Manipulation (TIle, Maximize, MInimize, etc) without asking for turning on 4-finger gesture for overview navigation. 

**The problem here being *Window Manipulation* is 3-finger Vertical direction gesture, which means until the default *Overview Navigation* gesture which uses 3-finger Vertical gesture is not overrided by extension managed 4-finger Overview navigation gesture, the setting is fruitless.**

This can be user interface enhancement to let user know what is required for what they want to achieve.

**Comment by harshadgavali** [comment]
window gesture do still work even with 3-finger overview gestures.
window gestures will switch to 4-finger in this case.
I agree this needs rework.

Are you facing this issue because of changes you made?
```
			ExtSettings.DEFAULT_OVERVIEW_GESTURE ? Clutter.Orientation.VERTICAL : Clutter.Orientation.HORIZONTAL,
			ExtSettings.DEFAULT_OVERVIEW_GESTURE ? true : false,
```
This change you made in PR messes the settings and is not actually needed at all.

**Comment by adhadse** [comment]
The changes I made. App navigation uses 3 finger HORIZONTAL gesture if 4 overview gesture is used otherwise switches to 4 finger VERTICAL gesture. (So this new PR gesture is not conflicting with Overview gesture)

Yeah, but this now would conflict with WIndow Manipulation. I personally don't really require Window Manipulation gesture and I'm better off with these new app navigation gesture with 4 fingers. 

But, I want to make this choice default since 3 finger app navigation + 3 finger window switching is difficult to perform.

**Comment by harshadgavali** [comment]
Closing this since this is only related to PR #98
